import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Words Count",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <h1 className="m-4 text-4xl font-extrabold leading-none tracking-tight text-white/20 md:text-5xl lg:text-6xl">Words Count</h1>
        <main className="mt-10">{children}</main>
      </body>
    </html>
  );
}
